#!/bin/bash
 
# Display All Hidden Dot Files In a Directory
# ls -a | egrep "^\." > backup_dotfiles.sh
DESTINATION="/home/moreno/Documentos/dotfiles"  # do not use a trailing slash (/)

 
# Colors
blue="\e[0;34m"
green="\e[1;32m"
red="\e[0;31m"
bold="\e[1;30m"
reset="\e[0m"
 
# file list (use trailing slash for directories)
FILES="
.applications/dwm*
.bashrc
.config/i3
.config/sublime-text-3
.config/openbox
.config/baraction.sh
.config/autostart.sh
.config/*.sh
.fonts/
.oh-my-zsh/
.profile
.spectrwm.conf
.vim*
.Xresources
.zsh_history
.zshrc
.zshrc.pre-oh-my-zsh
.xinitrc
dotfiles
"
for file in $FILES
do
   if [ -d $file ]; then
      mkdir -p $DESTINATION/$file
      rsync -vru $HOME/$file/* $DESTINATION/$file
   elif [ -f $file ]; then
      rsync -vru $HOME/$file $DESTINATION
   else
      echo -e "$red:: $file is not a file/directory! $reset"
   fi     
done
 
echo -e "$green:: Done! $reset"
exit 0
