#!/bin/bash

: '
Script bash for Custom menu on dmenu
for manage Screen Output

	by Adrian Moreno
	8/4/20
'


PROMPT="Screen Output"
OPTS="Laptop\nVGA Extended\nVGA Single\nManual"
#CHOISE=$(echo -e "$OPTS" | dmenu -i -p "$PROMPT" -nf '#FFFFFF' -nb '#002B36' -sb '#859900' -sf '#FFFFFF' -fn 'SFNS Display Bold-9' )
DIR="/home/moreno/.config/i3/scripts"
COM="[ "$(xrandr --query | awk '/VGA1/{print $2}')" = "disconnected" ]"

while getopts "dm:" opt; do

	case $opt in

		d) CHOISE=$(echo -e "$OPTS" | dmenu -i -p "$PROMPT" -nf '#FFFFFF' -nb '#002B36' -sb '#859900' -sf '#FFFFFF' -fn 'SFNS Display Bold-9') ;;

		m) CHOISE=$OPTARG ;;

		:) echo "-$OPTARG necesita argumento" >&2;
			exit 1 ;;

		\?) echo "Opcion -$OPTARG incorrecta" ;;
	esac
done


case $CHOISE in

	Laptop) xrandr --output LVDS1 --mode 1024x600 --output VGA1 --off ;;

	"VGA Single") $COM || ($DIR/1280x720 && xrandr --output LVDS1 --off) ;;

	"VGA Extended") $COM || $DIR/1280x720 ;;

	"Manual") arandr ;;

esac
