#!/bin/bash -x

MEM=$(free | awk '/Mem/{printf ("%.2f",$3/1000)}')
TOT=$(free | awk '/Mem/{printf ("%.2f",$2/1000)}')
PERC=$(echo "scale=2; ($MEM*100)/$TOT" | bc)


echo -e "${MEM}M (${PERC}%)\n"
#echo -e "${MEM}M (${PERC}%)\n"

[ $(echo "${PERC} > 75" | bc) -eq 1 ] && exit 33 || exit 0

